/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "./models";
import * as Mappers from "./models/mappers";
import { CarpoolContext } from "./carpoolContext";

class Carpool extends CarpoolContext {
  /**
   * Initializes a new instance of the Carpool class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param [options] The parameter options
   */
  constructor(credentials: msRest.ServiceClientCredentials, options?: Models.CarpoolOptions) {
    super(credentials, options);
  }

  /**
   * Sign up a new user
   * @summary Sign up
   * @param signUpDto
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  signUp(signUpDto: Models.SignUpDto, options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param signUpDto
   * @param callback The callback
   */
  signUp(signUpDto: Models.SignUpDto, callback: msRest.ServiceCallback<void>): void;
  /**
   * @param signUpDto
   * @param options The optional parameters
   * @param callback The callback
   */
  signUp(signUpDto: Models.SignUpDto, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  signUp(signUpDto: Models.SignUpDto, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.sendOperationRequest(
      {
        signUpDto,
        options
      },
      signUpOperationSpec,
      callback);
  }

  /**
   * Sign in an existing user
   * @summary Sign in
   * @param authDto
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  signIn(authDto: Models.AuthDto, options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param authDto
   * @param callback The callback
   */
  signIn(authDto: Models.AuthDto, callback: msRest.ServiceCallback<void>): void;
  /**
   * @param authDto
   * @param options The optional parameters
   * @param callback The callback
   */
  signIn(authDto: Models.AuthDto, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  signIn(authDto: Models.AuthDto, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.sendOperationRequest(
      {
        authDto,
        options
      },
      signInOperationSpec,
      callback);
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const signUpOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "api/v1/auth/signup",
  requestBody: {
    parameterPath: "signUpDto",
    mapper: {
      ...Mappers.SignUpDto,
      required: true
    }
  },
  responses: {
    200: {},
    default: {}
  },
  serializer
};

const signInOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "api/v1/auth/signin",
  requestBody: {
    parameterPath: "authDto",
    mapper: {
      ...Mappers.AuthDto,
      required: true
    }
  },
  responses: {
    200: {},
    default: {}
  },
  serializer
};

export {
  Carpool,
  CarpoolContext,
  Models as CarpoolModels,
  Mappers as CarpoolMappers
};
