/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";


/**
 * @interface
 * An interface representing SignUpDto.
 */
export interface SignUpDto {
  /**
   * @member {string} email
   */
  email: string;
  /**
   * @member {string} password
   */
  password: string;
  /**
   * @member {string} name
   */
  name: string;
}

/**
 * @interface
 * An interface representing AuthDto.
 */
export interface AuthDto {
  /**
   * @member {string} email
   */
  email: string;
  /**
   * @member {string} password
   */
  password: string;
}

/**
 * @interface
 * An interface representing CarpoolOptions.
 * @extends ServiceClientOptions
 */
export interface CarpoolOptions extends ServiceClientOptions {
  /**
   * @member {string} [baseUri]
   */
  baseUri?: string;
}
